### ISSUE TITLE
Insufficient Object Memory: Building on Alpine

### ISSUE THREAD

**Issue by IcedQuinn** [OpenSmalltalk/opensmalltalk-vm#519] opened 2020-09-03 01:55 UTC
Building via mvm scripts results in a VM that segfaults when attempting to load a Pharo 8 image.
Building via cmake requires some tweaks to compile (for example, SDL had to be told not to build Wayland support due to symbol duplication bugs) as well as adding `-Wl,--whole-archive /usr/lib/libexecinfo.a -Wl,--no-whole-archive` to the linker flags.
The compiled virtual machine results in a primitive failed exception and the VM is unusably slow.

`pharo` script must be modified to point the platform library path to `/lib` where libmusl lives.
cap flag has to be set to get around scheduling error `setcap cap_sys_nice=eip lib/pharo/pharo`

The error: `PrimitiveFailed: primitive #'insufficient object memory' in File class failed`
VM brand: `phcogspurlinuxspurmhdlssdl264+sdl2`

**Comment by eliotmiranda** [comment] 2020-09-03 02:37
I suggest you take this up with the "PharoVM" team who claim the VM as their own and profess to have the expertise to support it.

**Comment by IcedQuinn** [comment] 2020-09-03 09:27
this is an incredibly rude way to ask if the problem persists with other smalltalk images.

**Comment by krono** [comment] 2020-09-03 09:49
Hello there and welcome.

This might seem very strange to you, but there is a bit of history that leads to this outcome.

You report seems to indicate that you used a Pharo-issued VM and a Pharo image.

In that  case, your inital question might be better answered at https://github.com/pharo-project/opensmalltalk-vm

That repo states 

> This is a fork of OpenSmalltalk-vm. We are doing our best to keep compatibility and contribute back, as long as it fits the objective of Pharo community.

For seveal reasons, including a perceivedly low amount of "keep compatibility and contribute back" we cannot offer any support for VMs from that repo.

If you have used a VM from this repo and the error pops up with a non-Pharo image, please say so and we can reopen this issue.

**Comment by IcedQuinn** [comment] 2020-09-03 10:03
the VM was from this repo, that is why i reported it here.
the cmake files in this repo default to turning "pharo branding" on.
i launched a squeak 5 image and it did appear to throw out any primitive failures and the stock code browser was working correctly.
the VM also said to report here how to get it working since it did not recognize where libc was.

**Comment by krono** [comment] 2020-09-03 10:22
Thanks, can you give a few more hints about the primivite failures?

Please use the `mvm` script for now. Where there any significant warnings or errors during compilation  with MUSL?

**Comment by eliotmiranda** [comment] 2020-09-03 15:06
> On Sep 3, 2020, at 2:28 AM, IcedQuinn <notifications@github.com> wrote:
> 
> ﻿
> this is an incredibly rude way to ask if the problem persists with other smalltalk images.
> 
The PharoVM team’s behaviour is far worse than merely rude.  Your own assumption that I would support the PharoVM after all they have done and continue to do to steal credit and not contribute back could also be construed as rude, but perhaps it is merely ignorant. If the problem occurs in other images and non-Pharo builds of OpenSmalltalk perhaps you could provide steps to reproduce the problem.  Until that time my response to requests for support with a Pharo branded vm with be a firm rejection.

**Comment by krono** [comment] 2020-09-03 15:32
Ok, reopening and awaiting input on the Squeak primitve errors :)

**Comment by krono** [comment] 2020-09-03 15:32
(this is coordinated with @eliotmiranda , I'm assigning myself here)

**Comment by IcedQuinn** [comment] 2020-09-04 02:23
i apologize for cloning your repository and attempting to use it.
you may wish to modify your public README to better indicate new users are not welcome.
i will not be returning.

**Comment by krono** [comment] 2020-09-04 07:20
:(

**Comment by smalltalking** [comment] 2020-09-04 12:58
> you may wish to modify your public README to better indicate new users are not welcome.

That would be a lie, as new users are welcome here.
What should be written there is that the Pharo VMs in this repository are obsolete and unsupported. I see little to no value in having them built by the CI, but someone seems to disagree with that idea, as they are still there. Their presence may even be a source of confusion.
If Pharo 8 was really released with a VM from this repository, then that was a mistake by the Pharo team.
If you need a Pharo VM, you'll find it at [https://github.com/pharo-project/opensmalltalk-vm](https://github.com/pharo-project/opensmalltalk-vm).

**Comment by krono** [comment] 2020-09-05 10:28
Hi Pierce,

thanks for the info, but I don't see how these changes can alleviate the primitive erros.
But that said, maybe i can investigate the whole thing with the docker image, thank you.

**Comment by PierceNg** [comment] 2020-09-06 08:42
I read the first message again.

```
  PrimitiveFailed: primitive #'insufficient object memory' in File class failed
```

This looks familiar. When a Pharo 8 image starts, at some point it sends ```#primFileMasks``` to File, and I get a primitive failed error like the above on my laptop running Ubuntu 20.04.

The version of OpenSmalltalk VM that I built on this laptop is as follows:

```
  % ./pharo --version
  5.0-202007070220  Wed Jul  8 19:29:26 +08 2020 clang [Production Spur 64-bit VM]
  CoInterpreter VMMaker.oscog-eem.2772 uuid: 925a3892-829d-4417-bd5b-1a6a26678025 Jul  8 2020
  StackToRegisterMappingCogit VMMaker.oscog-eem.2771 uuid: a7ba3af0-70cc-4104-be1b-8895f533ed7b Jul  8 2020
  VM: 202007070220 pierce@Mailin:work/git/opensmalltalk/opensmalltalk-vm
  Date: Mon Jul 6 19:20:02 2020 CommitHash: 839a5cab0
  Plugins: 202007070220  pierce@Mailin:work/git/opensmalltalk/opensmalltalk-vm
  Linux Mailin 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  plugin path: /home/pierce/pkg/osvmp8/ [default: /home/pierce/pkg/osvmp8/]
```

I have an older version of the VM as well, built on another laptop that has since crashed:

```
  % ./pharo -version
  5.0-201808291622  Thu Sep 20 22:32:45 +08 2018 gcc 5.4.0 [Production Spur 64-bit VM]
  CoInterpreter VMMaker.oscog-eem.2437 uuid: 0e97c106-dd0b-437b-b1aa-e15257288c3f Sep 20 2018
  StackToRegisterMappingCogit VMMaker.oscog-eem.2432 uuid: 7b14d114-0e04-4e46-b8a7-4b5e6d87f5fe Sep 20 2018
  VM: 201808291622 pierce@othas:src/st/opensmalltalk-vm
  Date: Wed Aug 29 09:22:35 2018 CommitHash: d952580
  Plugins: 201808291622 pierce@othas:src/st/opensmalltalk-vm
  Linux othas 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  plugin path: /home/pierce/pkg/osvmp6/ [default: /home/pierce/pkg/osvmp6/]
```

With this version, ```File primFileMasks``` produces the following which I hope is the expected output:

```
  #(61440 49152 40960 32768 24576 16384 8192 4096)
```

If I copy the older VM's ```FileAttributePlugin.so``` over the newer VM's, it produces the same output on Pharo 8 with the newer VM, no primitive error.

I don't know the VM internals enough to investigate, but looks like it is possible to start bisecting from VMMaker.oscog-eem.2772 and VMMaker.oscog-eem.2437 or thereabouts.

**Comment by smalltalking** [comment] 2020-09-06 13:02
The main difference I see is that the "old" code created an Array while the "new" tries to create a WordArray.
https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/3a4ebae28c183dd49ea9e494cd7bcd2ec0d687fa#diff-04cbc775a3686446b844a93e1520e706R755

**Comment by eliotmiranda** [comment] 2020-09-06 16:21
Should be fixed by https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/e58cec1e82b60535dbe666b511c1c2198f7921f9.  Please test to confirm and close if ok.

**Comment by krono** [comment] 2020-09-06 16:56
Thank you!

**Comment by PierceNg** [comment] 2020-09-07 02:06
Eliot,

Thank you. I made the below changes to FileAttributesPlugin.c.  With these changes, ```File primFileMasks``` on
Pharo 8 produces output and no longer throws primitive failed error.

```
--- a/src/plugins/FileAttributesPlugin/FileAttributesPlugin.c
+++ b/src/plugins/FileAttributesPlugin/FileAttributesPlugin.c
@@ -97,7 +97,7 @@ EXPORT(sqInt) primitiveClosedir(void);
 EXPORT(sqInt) primitiveFileAttribute(void);
 EXPORT(sqInt) primitiveFileAttributes(void);
 EXPORT(sqInt) primitiveFileExists(void);
-static sqInt primitiveFileMasks(void);
+EXPORT(sqInt) primitiveFileMasks(void);
 EXPORT(sqInt) primitiveLogicalDrives(void);
 EXPORT(sqInt) primitiveOpendir(void);
 EXPORT(sqInt) primitivePathMax(void);
@@ -746,7 +746,7 @@ primitiveFileExists(void)
 /*     Answer an array (or word array) of well known file masks */

        /* FileAttributesPlugin>>#primitiveFileMasks */
-static sqInt
+EXPORT(sqInt)
 primitiveFileMasks(void)
 {
     sqInt * masks;
@@ -765,6 +765,7 @@ primitiveFileMasks(void)
        }
        masks = ((sqInt *) (firstIndexableField(masksArray)));
        nilObj = nilObject();
+       masks[0] = (integerObjectOf(S_IFMT));
 #  if defined(S_IFSOCK)
        masks[1] = (integerObjectOf(S_IFSOCK));
 #  else
```

**Comment by PierceNg** [comment] 2020-09-09 00:04
Tested successfully with https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/1b896e93195458099ac6cb27c5bb85dec66501d2. Thank you Eliot.

**Closed as completed** 2020-09-09 06:07 UTC
