### ISSUE TITLE
config.h:40:2: error: This file was included too late. Please make sure it is included earlier

### ISSUE THREAD

**Issue by asarch** [OpenSmalltalk/opensmalltalk-vm#567] opened 2021-05-20 03:25 UTC
This is what happens in Debian 10 Buster for AMD64:

[compilacion.log](https://github.com/OpenSmalltalk/opensmalltalk-vm/files/6512643/compilacion.log)

**Comment by nicolas-cellier-aka-nice** [comment] 2021-05-20 22:30
Duplicate of #560

**Closed as completed by nicolas-cellier-aka-nice** 2021-05-20 22:30 UTC
